"""
Deploy Foundry Agents for MongoDB data analysis via YARP proxy.

Three agents are created, each focused on a different analytical lens
over the data generated by mongo-data-generator:

  ContractAnalyst         – portfolio composition and maturity risk
  RiskMemoInvestigator    – severity patterns across risk memos
  MarketDataSurveillance  – spot and volatility trend detection

All three agents connect through the YARP proxy, which enforces API-key
auth before forwarding requests to the in-cluster MongoDB MCP server.

Usage:
    python scripts/deploy_foundry_agents.py \\
        --project-endpoint  <PROJECT_ENDPOINT> \\
        --model-deployment  <MODEL_DEPLOYMENT_NAME> \\
        --mcp-proxy-url     <YARP_PROXY_MCP_URL> \\
        --mcp-api-key       <PROXY_API_KEY>

Options:
    --mcp-proxy-url     Full MCP endpoint on the YARP proxy, e.g.
                        http://yarp-proxy.mcp-tools.svc.cluster.local/mcp
    --mcp-api-key       Value for the X-Api-Key header the proxy enforces
    --connection-name   Name of the AI Foundry project connection that stores
                        the proxy API key (created by Deploy-FoundryAgents.ps1).
                        Passed directly as project_connection_id on MCPTool;
                        Agent Service retrieves the key from the connection at
                        runtime and injects it into MCP requests automatically.
    --cleanup           Delete existing agent versions before re-creating
"""

import sys
import argparse
from typing import Dict

from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient
from azure.ai.projects.models import PromptAgentDefinition


class AgentDeployer:
    """Create and manage Foundry agents that analyse data in MongoDB via the
    YARP proxy → MongoDB MCP server pipeline."""

    def __init__(
        self,
        project_endpoint: str,
        model_deployment: str,
        mcp_proxy_url: str,
        mcp_api_key: str,
        connection_name: str = "",
    ):
        self.project_endpoint = project_endpoint
        self.model_deployment = model_deployment
        self.mcp_proxy_url = mcp_proxy_url
        self.mcp_api_key = mcp_api_key
        self.connection_name = connection_name

        self.project_client = AIProjectClient(
            endpoint=project_endpoint,
            credential=DefaultAzureCredential(),
        )

        # track created agents for optional cleanup
        self._created: list[Dict] = []

    # ── helpers ──────────────────────────────────────────────────────────────

    def _create_agent(self, name: str, instructions: str) -> Dict:
        agent = self.project_client.agents.create_version(
            agent_name=name,
            definition=PromptAgentDefinition(
                model=self.model_deployment,
                instructions=instructions,
            ),
        )
        self._created.append({"name": agent.name, "version": agent.version})
        print(f"  OK  {name}  (id: {agent.id}, version: {agent.version})")
        return {"id": agent.id, "name": agent.name, "version": agent.version}
    
    # ── agents ────────────────────────────────────────────────────────────────

    def create_contract_analyst(self) -> Dict:
        """Portfolio composition and maturity-risk agent.

        Analyses the `contracts` collection for desk/book breakdowns,
        counterparty concentration, large notionals, and upcoming maturities.
        """
        instructions = """
You are ContractAnalyst, a portfolio analyst with read access to a MongoDB database
through the 'mongodb' MCP server.

## Connection
- The MongoDB connection is pre-configured on the server via environment variable.
- Do NOT call connect() with a connection string — just use the database tools directly.
- Target database: contracts_db
- Primary collection: contracts

## Contract document shape
{
  contractId, book, desk, counterparty, currencyPair,
  notional (numeric, USD), maturityDate (YYYY-MM-DD), status, createdAt, updatedAt
}

## When asked to analyse the portfolio:

1. Overview
   - Total contract count (find with empty filter and count)
   - Breakdown by status (new / active / amended / closed)

2. Concentration risk
   - Top 10 counterparties by total notional (aggregate $group + $sort)
   - Breakdown by desk and by book

3. Maturity risk
   - Contracts maturing within 90 days from today
   - Flag any single counterparty with > 20 % of total notional

4. Currency exposure
   - Aggregate total notional per currencyPair
   - Identify the largest single-pair exposure as a % of total

5. Summary memo
   - Produce a plain-English risk summary covering concentration, maturity,
     and currency findings.  Cite specific counterparty names and numbers.

## Rules
- Only use data retrieved from the MCP tools.  Do not fabricate values.
- If a query returns no results, state that clearly and move on.
- Use $group / $sort aggregations for rollups; do not do arithmetic in your head.
- Always quote specific values (counts, notionals, dates) in your output.
"""
        return self._create_agent("ContractAnalyst", instructions)
    
    def create_risk_memo_investigator(self) -> Dict:
        """Risk memo severity pattern agent.

        Cross-references the `risk_memos` and `contracts` collections to surface
        high-severity patterns, desk hotspots, and DV01 / VaR outliers.
        """
        instructions = """
You are RiskMemoInvestigator, a risk analyst with read access to a MongoDB database
through the 'mongodb' MCP server.

## Connection
- The MongoDB connection is pre-configured on the server via environment variable.
- Do NOT call connect() with a connection string — just use the database tools directly.
- Target database: contracts_db
- Primary collection: risk_memos
- Secondary collection: contracts

## Risk memo document shape
{
  memoId, contractId, summary, var95 (numeric), dv01 (numeric),
  severity ("high" | "medium"), createdAt
}

## When asked to investigate risk memos:

1. Summary counts
   - Total memos
   - Count by severity (high / medium)
   - Average and max var95 and dv01 across all memos

2. High-severity deep dive
   - Retrieve the 20 highest var95 memos
   - For each, look up the contract document to get desk, book, counterparty
   - Group by desk and counterparty to find hotspots

3. DV01 outliers
   - Find memos where abs(dv01) > 60000
   - List affected contractIds with dv01 value and counterparty name

4. Trend over time
   - Aggregate memo counts by createdAt date (truncate to hour or day)
   - Identify any spikes in high-severity memos

5. Integrated risk narrative
   - Combine findings into a structured report:
       * Executive summary (2-3 sentences)
       * Top risk concentrations (desk / counterparty / currency pair)
       * Recommended monitoring priorities

## Rules
- Always join memo data to contracts via contractId to get desk/counterparty context.
- Use aggregate queries with $lookup or sequential find queries if $lookup is unavailable.
- Do not invent data; state "not found" if a join produces no match.
- Report absolute values for dv01 in your narrative (it can be negative).
"""
        return self._create_agent("RiskMemoInvestigator", instructions)
    
    def create_market_data_surveillance(self) -> Dict:
        """Spot price and volatility surveillance agent.

        Analyses the `market_data` collection for trends, volatility spikes,
        and anomalous readings across currency pairs in the synthetic dataset.
        """
        instructions = """
You are MarketDataSurveillance, a quantitative analyst with read access to a MongoDB
database through the 'mongodb' MCP server.

## Connection
- The MongoDB connection is pre-configured on the server via environment variable.
- Do NOT call connect() with a connection string — just use the database tools directly.
- Target database: contracts_db
- Primary collection: market_data

## Market data document shape
{
  snapshotId, currencyPair, spot (numeric), volatility (numeric, e.g. 0.12 = 12%%),
  asOf (ISODate), source
}

## When asked to run a market surveillance report:

1. Inventory
   - Total snapshot count
   - Distinct currency pairs present

2. Per-pair statistics
   For each currency pair, compute (via aggregate):
   - min, max, average spot
   - min, max, average volatility (express as %%)
   - Number of snapshots

3. Volatility alerts
   - Find all snapshots where volatility > 0.20 (20%%)
   - Report by currency pair: count of breaches, highest breach value, time of highest breach

4. Spot range analysis
   - For each pair, identify the time window with the widest spot range
   - Flag pairs where max/min ratio > 1.10 (more than 10%% range)

5. Most recent snapshot
   - Retrieve the latest asOf timestamp in the collection
   - Show spot and volatility for each pair as of that snapshot

6. Narrative summary
   - Highlight the most volatile pair, the pair with the widest spot range,
     and any concerning data quality issues (e.g., duplicate snapshots, gaps).

## Rules
- Use aggregate with $group to compute stats; do not manually average in your head.
- Express volatility as percentage in the narrative (multiply by 100).
- If there are fewer than 10 snapshots for a pair, note it may be statistically thin.
- Do not fabricate values; cite exact figures from query results.
"""
        return self._create_agent("MarketDataSurveillance", instructions)
    
    # ── orchestration ─────────────────────────────────────────────────────────

    def deploy_all(self) -> Dict:
        _hdr = "=" * 68
        print(f"\n{_hdr}")
        print("  Deploying MongoDB Analysis Agents via YARP Proxy")
        print(_hdr)
        print(f"  Project endpoint : {self.project_endpoint}")
        print(f"  Model deployment : {self.model_deployment}")
        print(f"{_hdr}\n")

        results = {}
        try:
            results["contract_analyst"]         = self.create_contract_analyst()
            results["risk_memo_investigator"]    = self.create_risk_memo_investigator()
            results["market_data_surveillance"]  = self.create_market_data_surveillance()
        except Exception as exc:
            print(f"\n  ERROR: {exc}")
            import traceback; traceback.print_exc()
            sys.exit(1)

        print(f"\n{_hdr}")
        print("  All agents deployed successfully")
        print(_hdr)
        for key, agent in results.items():
            print(f"  {agent['name']}")
            print(f"    id      : {agent['id']}")
            print(f"    version : {agent['version']}")

        print(f"\n{_hdr}")
        print("  Next steps")
        print(_hdr)
        print("  1. Ensure mongo-data-generator has seeded data into contracts_db")
        print("  2. In the Foundry portal, add the MCP tool to each agent:")
        print("       Tool type  : Remote MCP Server")
        print("       URL        : http://<yarp-proxy-ip>/mcp")
        print("       Connection : yarp-proxy-mcp  (Custom Keys, api-key header)")
        print("  3. Test interactively via Notebook/01_azure_ai_agent-mcp.ipynb")
        print()

        return results

    def cleanup(self):
        print("\n  Cleaning up agents...")
        for entry in self._created:
            try:
                self.project_client.agents.delete_version(
                    agent_name=entry["name"],
                    agent_version=entry["version"],
                )
                print(f"  deleted  {entry['name']}  v{entry['version']}")
            except Exception as exc:
                print(f"  WARN     could not delete {entry['name']}: {exc}")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Deploy MongoDB analysis agents for the MCP YARP proxy project"
    )
    parser.add_argument("--project-endpoint", required=True,
        help="Microsoft Foundry project endpoint URL")
    parser.add_argument("--model-deployment", required=True,
        help="Model deployment name (e.g. gpt-4o)")
    parser.add_argument("--mcp-proxy-url",
        default="http://yarp-proxy.mcp-tools.svc.cluster.local/mcp",
        help="Full MCP endpoint on the YARP proxy (default: AKS in-cluster URL)")
    parser.add_argument("--mcp-api-key", default="",
        help="API key value (used only if --connection-name is not supplied)")
    parser.add_argument("--connection-name", default="",
        help="AI Foundry project connection name that stores the proxy API key")
    parser.add_argument("--cleanup", action="store_true",
        help="Delete created agent versions after deployment (useful for dev iteration)")

    args = parser.parse_args()

    deployer = AgentDeployer(
        project_endpoint=args.project_endpoint,
        model_deployment=args.model_deployment,
        mcp_proxy_url=args.mcp_proxy_url,
        mcp_api_key=args.mcp_api_key,
        connection_name=args.connection_name,
    )

    deployer.deploy_all()

    if args.cleanup:
        deployer.cleanup()


if __name__ == "__main__":
    main()

